name: ServerseCore
version: '${project.version}'
main: io.github.varatros.serversecore.ServerseCore
api-version: 1.18
authors: [ Varatros ]
description: Core plugin used by Serverse
website: github.com/Varatros

commands:
  map:
    description: Links the map in chat.
  twitch:
    description: Links twitch affiliates in chat.
  shrug:
    description: Shrugs.
  commandspy:
    aliases: [cmdspy, cspy, cs]
    permission: serverse.staff
    permission-message: You do not have permission to use this command.
    description: CommandSpy.

permissions:
  serverse.*:
    description: Wildcard permission
    default: op
    children:
      serverse.admin: true
      serverse.staff: true
  serverse.admin:
    description: Serverse admin permission
    children:
      serverse.staff: true
  serverse.staff:
    description: Serverse staff permission
